id: I1921BA49
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:09:08+00:00'
last_modified: '2022-06-07T20:29:08.319321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD133161
  title: ཤར་རྫ་པ་བཀྲ་ཤིས་རྒྱལ་མཚན་གྱི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2F72:
      image_group_id: I4PD2789
      title: ''
      total_pages: 464
      order: 1
      base_file: 2F72.txt
    F52E:
      image_group_id: I4PD2790
      title: ''
      total_pages: 562
      order: 2
      base_file: F52E.txt
    18F5:
      image_group_id: I4PD2791
      title: ''
      total_pages: 558
      order: 3
      base_file: 18F5.txt
    '5987':
      image_group_id: I4PD2792
      title: ''
      total_pages: 506
      order: 4
      base_file: 5987.txt
    C4CE:
      image_group_id: I4PD2793
      title: ''
      total_pages: 382
      order: 5
      base_file: C4CE.txt
    8B84:
      image_group_id: I4PD2794
      title: ''
      total_pages: 392
      order: 6
      base_file: 8B84.txt
    4F82:
      image_group_id: I4PD2795
      title: ''
      total_pages: 546
      order: 7
      base_file: 4F82.txt
    AE7F:
      image_group_id: I4PD2796
      title: ''
      total_pages: 478
      order: 8
      base_file: AE7F.txt
    2F15:
      image_group_id: I4PD2797
      title: ''
      total_pages: 448
      order: 9
      base_file: 2F15.txt
    5A8F:
      image_group_id: I4PD2798
      title: ''
      total_pages: 512
      order: 10
      base_file: 5A8F.txt
    '3441':
      image_group_id: I4PD2799
      title: ''
      total_pages: 422
      order: 11
      base_file: 3441.txt
    4AD1:
      image_group_id: I4PD2800
      title: ''
      total_pages: 406
      order: 12
      base_file: 4AD1.txt
    17A8:
      image_group_id: I4PD2801
      title: ''
      total_pages: 418
      order: 13
      base_file: 17A8.txt
    9E15:
      image_group_id: I4PD2802
      title: ''
      total_pages: 504
      order: 14
      base_file: 9E15.txt
    B73A:
      image_group_id: I4PD2803
      title: ''
      total_pages: 342
      order: 15
      base_file: B73A.txt
    '9205':
      image_group_id: I4PD2804
      title: ''
      total_pages: 354
      order: 16
      base_file: 9205.txt
    EA8F:
      image_group_id: I4PD2805
      title: ''
      total_pages: 362
      order: 17
      base_file: EA8F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
